Update main_stanfordforecastapp.yml

diff --git a/.github/workflows/main_stanfordforecastapp.yml b/.github/workflows/main_stanfordforecastapp.yml
--- a/.github/workflows/main_stanfordforecastapp.yml
+++ b/.github/workflows/main_stanfordforecastapp.yml
@@ -14,10 +14,13 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
+      contents: read # This is required for actions/checkout
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: List files before installing dependencies
+        run: ls -al
 
       - name: Set up Python version
         uses: actions/setup-python@v5
@@ -28,14 +31,19 @@ jobs:
         run: |
           python -m venv venv
           source venv/bin/activate
-      
+
       - name: Install dependencies
-        run: pip install -r ./requirements.txt
+        run: |
+          if [ -f requirements.txt ]; then
+            pip install -r requirements.txt
+          else
+            echo "ERROR: requirements.txt not found!"
+            exit 1
+          fi
         
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
       - name: Run Flask app
         run: python app.py
-
 
       - name: Zip artifact for deployment
         run: zip release.zip ./* -r
@@ -46,6 +54,7 @@ jobs:
           name: python-app
           path: |
             release.zip
+            requirements.txt
             !venv/
 
   deploy:
@@ -55,8 +64,8 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
+      id-token: write # This is required for requesting the JWT
+      contents: read # This is required for actions/checkout
 
     steps:
       - name: Download artifact from build job
@@ -67,18 +76,16 @@ jobs:
       - name: Unzip artifact for deployment
         run: unzip release.zip
 
-      
       - name: Login to Azure
         uses: azure/login@v2
         with:
-          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6CACAAC7CCB4F96A3A03B9124CFA901 }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11E9FC3175064A13B95B530E3CDDA0DF }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E1D872F41E143DCABA68A73CD3E89D4 }}
+          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
+          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
+          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
 
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
         id: deploy-to-webapp
         with:
           app-name: 'StanfordForecastApp'
           slot-name: 'Production'
-          
